XTA: API Reference for C language
xta_iface_s Struct Reference
#include <xta_iface.h>
Data Fields
long flags
char name [RMNAMESZ]
long version
int(* xa_close_entry)(xta_xa_resource_t *, char *, int, long)
int(* xa_commit_entry)(xta_xa_resource_t *, const XID *, int, long)
int(* xa_end_entry)(xta_xa_resource_t *, const XID *, int, long)
int(* xa_forget_entry)(xta_xa_resource_t *, const XID *, int, long)
int(* xa_open_entry)(xta_xa_resource_t *, char *, int, long)
int(* xa_prepare_entry)(xta_xa_resource_t *, const XID *, int, long)
int(* xa_recover_entry)(xta_xa_resource_t *, XID *xids, long, int, long)
int(* xa_rollback_entry)(xta_xa_resource_t *, const XID *, int, long)
int(* xa_start_entry)(xta_xa_resource_t *, const XID *, int, long)
Detailed Description
XTA interface that are used to collect the function pointers
Definition at line 34 of file xta_iface.h.
Field Documentation
long xta_iface_s::flags
options specific to the resource manager
Definition at line 42 of file xta_iface.h.
Referenced by lixa_iface_get_flags().
char xta_iface_s::name[RMNAMESZ]
name of resource manager
Definition at line 38 of file xta_iface.h.
Referenced by lixa_iface_get_name().
long xta_iface_s::version
must be 0
Definition at line 46 of file xta_iface.h.
int(* xta_iface_s::xa_close_entry)(xta_xa_resource_t *, char *, int, long)
xa_close function pointer
Definition at line 54 of file xta_iface.h.
Referenced by lixa_iface_xa_close().
int(* xta_iface_s::xa_commit_entry)(xta_xa_resource_t *, const XID *, int, long)
xa_commit function pointer
Definition at line 74 of file xta_iface.h.
Referenced by lixa_iface_xa_commit().
int(* xta_iface_s::xa_end_entry)(xta_xa_resource_t *, const XID *, int, long)
xa_end function pointer
Definition at line 62 of file xta_iface.h.
Referenced by lixa_iface_xa_end().
int(* xta_iface_s::xa_forget_entry)(xta_xa_resource_t *, const XID *, int, long)
xa_forget function pointer
Definition at line 82 of file xta_iface.h.
Referenced by lixa_iface_xa_forget().
int(* xta_iface_s::xa_open_entry)(xta_xa_resource_t *, char *, int, long)
xa_open function pointer
Definition at line 50 of file xta_iface.h.
Referenced by lixa_iface_xa_open().
int(* xta_iface_s::xa_prepare_entry)(xta_xa_resource_t *, const XID *, int, long)
xa_prepare function pointer
Definition at line 70 of file xta_iface.h.
Referenced by lixa_iface_xa_prepare().
int(* xta_iface_s::xa_recover_entry)(xta_xa_resource_t *, XID *xids, long, int, long)
xa_recover function pointer
Definition at line 78 of file xta_iface.h.
Referenced by lixa_iface_xa_recover().
int(* xta_iface_s::xa_rollback_entry)(xta_xa_resource_t *, const XID *, int, long)
xa_rollback function pointer
Definition at line 66 of file xta_iface.h.
Referenced by lixa_iface_xa_rollback().
int(* xta_iface_s::xa_start_entry)(xta_xa_resource_t *, const XID *, int, long)
xa_start function pointer
Definition at line 58 of file xta_iface.h.
Referenced by lixa_iface_xa_start().
The documentation for this struct was generated from the following file:
xta_iface.h
Copyright © 2009-2019, Christian Ferrari tiian@users.sourceforge.net http://www.tiian.org/