XTA: API Reference for C language
xa_switch_t Struct Reference
#include <xa.h>
Data Fields
long flags
char name [RMNAMESZ]
long version
int(* xa_close_entry)(char *, int, long)
int(* xa_commit_entry)(const XID *, int, long)
int(* xa_complete_entry)(int *, int *, int, long)
int(* xa_end_entry)(const XID *, int, long)
int(* xa_forget_entry)(const XID *, int, long)
int(* xa_open_entry)(char *, int, long)
int(* xa_prepare_entry)(const XID *, int, long)
int(* xa_recover_entry)(XID *, long, int, long)
int(* xa_rollback_entry)(const XID *, int, long)
int(* xa_start_entry)(const XID *, int, long)
Detailed Description
XA switch data structure
Definition at line 76 of file xa.h.
Field Documentation
long xa_switch_t::flags
options specific to the resource manager
Definition at line 85 of file xa.h.
Referenced by lixa_iface_get_flags().
char xa_switch_t::name[RMNAMESZ]
name of resource manager
Definition at line 81 of file xa.h.
Referenced by lixa_iface_get_name().
long xa_switch_t::version
must be 0
Definition at line 89 of file xa.h.
int(* xa_switch_t::xa_close_entry)(char *, int, long)
xa_close function pointer
Definition at line 97 of file xa.h.
Referenced by lixa_iface_xa_close().
int(* xa_switch_t::xa_commit_entry)(const XID *, int, long)
xa_commit function pointer
Definition at line 117 of file xa.h.
Referenced by lixa_iface_xa_commit().
int(* xa_switch_t::xa_complete_entry)(int *, int *, int, long)
xa_complete function pointer
Definition at line 129 of file xa.h.
int(* xa_switch_t::xa_end_entry)(const XID *, int, long)
xa_end function pointer
Definition at line 105 of file xa.h.
Referenced by lixa_iface_xa_end().
int(* xa_switch_t::xa_forget_entry)(const XID *, int, long)
xa_forget function pointer
Definition at line 125 of file xa.h.
Referenced by lixa_iface_xa_forget().
int(* xa_switch_t::xa_open_entry)(char *, int, long)
xa_open function pointer
Definition at line 93 of file xa.h.
Referenced by lixa_iface_xa_open().
int(* xa_switch_t::xa_prepare_entry)(const XID *, int, long)
xa_prepare function pointer
Definition at line 113 of file xa.h.
Referenced by lixa_iface_xa_prepare().
int(* xa_switch_t::xa_recover_entry)(XID *, long, int, long)
xa_recover function pointer
Definition at line 121 of file xa.h.
Referenced by lixa_iface_xa_recover().
int(* xa_switch_t::xa_rollback_entry)(const XID *, int, long)
xa_rollback function pointer
Definition at line 109 of file xa.h.
Referenced by lixa_iface_xa_rollback().
int(* xa_switch_t::xa_start_entry)(const XID *, int, long)
xa_start function pointer
Definition at line 101 of file xa.h.
Referenced by lixa_iface_xa_start().
The documentation for this struct was generated from the following file:
xa.h
Copyright © 2009-2018, Christian Ferrari tiian@users.sourceforge.net http://www.tiian.org/