XTA: API Reference for C language
xta_acquired_xa_resource.c File Reference
#include "config.h"
#include "lixa_errors.h"
#include "lixa_trace.h"
#include "xta_acquired_xa_resource.h"
Macros
#define LIXA_TRACE_MODULE LIXA_TRACE_MOD_XTA
Functions
void xta_acquired_xa_resource_clean (xta_acquired_xa_resource_t *xa_resource)
int xta_acquired_xa_resource_init (xta_acquired_xa_resource_t *xa_resource, const struct xta_iface_s *iface, const char *name, const char *open_info)
Macro Definition Documentation
#define LIXA_TRACE_MODULE LIXA_TRACE_MOD_XTA
Definition at line 44 of file xta_acquired_xa_resource.c.
Function Documentation
void xta_acquired_xa_resource_clean (xta_acquired_xa_resource_t * xa_resource)
Clean the common properties of Acquired XA Resources; this function must be called after xta_acquired_xa_resource_init during object deletion to avoid memory leaks
Parameters
[in,out] xa_resource : Acquired XA Resource object
Definition at line 140 of file xta_acquired_xa_resource.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_NULL_OBJECT, LIXA_RC_OK, xta_xa_resource_s::rsrmgr_config, and xta_acquired_xa_resource_t::xa_resource.
Referenced by xta_mysql_xa_resource_clean(), and xta_postgresql_xa_resource_clean().
int xta_acquired_xa_resource_init (xta_acquired_xa_resource_t * xa_resource, const struct xta_iface_s * iface, const char * name, const char * open_info)
Initialize the common properties of Acquired XA Resources
Parameters
[in,out] xa_resource : Acquired XA Resource object
[in] iface : interface with XA function pointers
[in] name : unique identifier of the resource
[in] open_info : unique description of the connection properties like network name/IP address, port, user/schema, etc. Only the first MAXINFOSIZE characters will be kept.
Returns
a reason code
Definition at line 48 of file xta_acquired_xa_resource.c.
References xta_acquired_xa_resource_t::iface, LIXA_RC_INTERNAL_ERROR, LIXA_RC_INVALID_OPTION, LIXA_RC_NULL_OBJECT, LIXA_RC_OBJ_CORRUPTED, LIXA_RC_OK, LIXA_RC_XML_STRDUP_ERROR, MAXINFOSIZE, xta_xa_resource_s::rsrmgr_config, xta_acquired_xa_resource_t::xa_resource, and xta_xa_resource_init().
Referenced by xta_mysql_xa_resource_init(), and xta_postgresql_xa_resource_init().
Copyright © 2009-2019, Christian Ferrari tiian@users.sourceforge.net http://www.tiian.org/