XTA: XA Transaction API (LIXA: Free/Open Source Software XA Transaction Manager)
client_config.h File Reference
#include <config.h>
#include "lixa_trace.h"
#include "lixa_config.h"
#include "xa.h"
#include "lixa_iface.h"
Data Structures
struct act_rsrmgr_config_s
struct actual_config_s
struct client_config_coll_s
struct profile_config_s
struct rsrmgr_config_s
struct sttsrv_config_s
Macros
#define LIXA_CONFIG_FILE_ENV_VAR "LIXA_CONFIG_FILE"
#define LIXA_JOB_ENV_VAR "LIXA_JOB"
#define LIXA_PROFILE_ENV_VAR "LIXA_PROFILE"
#define LIXA_TRACE_MODULE LIXA_TRACE_MOD_CLIENT_CONFIG
#define LIXA_TRACE_MODULE LIXA_TRACE_MODULE_SAVE
#define LIXA_TRACE_MODULE_SAVE LIXA_TRACE_MODULE
Typedefs
typedef struct client_config_coll_s client_config_coll_t
Functions
int client_config (client_config_coll_t *ccc, int global_config)
void client_config_append_rsrmgr (client_config_coll_t *ccc, const struct rsrmgr_config_s *rsrmgr, const struct act_rsrmgr_config_s *act_rsrmgr)
int client_config_display (client_config_coll_t *ccc)
void client_config_display_rsrmgr (const struct act_rsrmgr_config_s *arc)
int client_config_dup (const client_config_coll_t *source, client_config_coll_t *target)
static struct sttsrv_config_s * client_config_get_sttsrv (const client_config_coll_t *ccc)
int client_config_job (client_config_coll_t *ccc, int fd)
int client_config_load_all_switch_files (client_config_coll_t *ccc)
int client_config_load_switch_file (struct act_rsrmgr_config_s *act_rsrmgr, int dynamically_defined)
int client_config_rsrmgr_dup (const struct act_rsrmgr_config_s *arc, struct rsrmgr_config_s *rsrmgr, struct act_rsrmgr_config_s *act_rsrmgr)
gchar * client_config_tostring_rsrmgr (const struct act_rsrmgr_config_s *arc)
int client_config_unload_all_switch_files (client_config_coll_t *ccc)
int client_config_unload_switch_file (struct act_rsrmgr_config_s *act_rsrmgr)
int client_config_validate (client_config_coll_t *ccc)
int client_parse (struct client_config_coll_s *ccc, xmlNode *a_node)
int client_parse_profile (struct client_config_coll_s *ccc, xmlNode *a_node)
int client_parse_profile_rsrmgrs (struct client_config_coll_s *ccc, xmlNode *a_node, GArray *rsrmgrs)
int client_parse_profile_sttsrvs (struct client_config_coll_s *ccc, xmlNode *a_node, GArray *sttsrvs)
int client_parse_profiles (struct client_config_coll_s *ccc, xmlNode *a_node)
int client_parse_rsrmgr (struct client_config_coll_s *ccc, xmlNode *a_node)
int client_parse_rsrmgrs (struct client_config_coll_s *ccc, xmlNode *a_node)
int client_parse_sttsrv (struct client_config_coll_s *ccc, xmlNode *a_node)
int client_parse_sttsrvs (struct client_config_coll_s *ccc, xmlNode *a_node)
int client_unconfig (client_config_coll_t *ccc, int global_config)
Macro Definition Documentation
#define LIXA_CONFIG_FILE_ENV_VAR "LIXA_CONFIG_FILE"
Name of the environment variable must be uset to specify the client config file name
Definition at line 81 of file client_config.h.
#define LIXA_JOB_ENV_VAR "LIXA_JOB"
Name of the environment variable must be uset to specify the job
Definition at line 88 of file client_config.h.
#define LIXA_PROFILE_ENV_VAR "LIXA_PROFILE"
Name of the environment variable must be used to specify the profile
Definition at line 73 of file client_config.h.
#define LIXA_TRACE_MODULE LIXA_TRACE_MOD_CLIENT_CONFIG
Definition at line 592 of file client_config.h.
#define LIXA_TRACE_MODULE LIXA_TRACE_MODULE_SAVE
Definition at line 592 of file client_config.h.
#define LIXA_TRACE_MODULE_SAVE LIXA_TRACE_MODULE
Definition at line 61 of file client_config.h.
Typedef Documentation
typedef struct client_config_coll_s client_config_coll_t
It contains the configuration for the client if (profile == NULL) the configuration must be loaded else the configuration has already been loaded
Function Documentation
int client_config (client_config_coll_t * ccc, int global_config)
Load configuration from environment vars and XML files
Parameters
[out] ccc : the object that will contain the client configuration
[in] global_config : TRUE if "ccc" is a global static object (just one for all the threads of the process) , FALSE if "ccc" is a local dynamic object (every thread has its own). TX API uses a global static config shared by all the threads, XTA API uses a local dynamic object for every thread.
Returns
a reason code
Referenced by xta_transaction_manager_new().
void client_config_append_rsrmgr (client_config_coll_t * ccc, const struct rsrmgr_config_s * rsrmgr, const struct act_rsrmgr_config_s * act_rsrmgr)
Append a resource manager to the list of actual resource managers
Parameters
[in,out] ccc : client config collection object
[in] rsrmgr : describes the resource manager that must be appended (it can be NULL)
[in] act_rsrmgr : that describes the actual resource manager that must be appended (it can be NULL)
Referenced by xta_transaction_enlist_resource().
int client_config_display (client_config_coll_t * ccc)
Display configuration read from XML config file
Parameters
[in] ccc : the object that will contain the client configuration
Returns
a standardized return code
Referenced by xta_transaction_new().
void client_config_display_rsrmgr (const struct act_rsrmgr_config_s * arc)
Display the configuration of an actual resource manager (debugging purpose only)
Parameters
[in] arc : actual resource manager config
int client_config_dup (const client_config_coll_t * source, client_config_coll_t * target)
Duplicate a client configuration collection. The target object must be cleared with client_unconfig when it's no more necessary.
Parameters
[in] source configuration object
[out] target configuration object
Returns
a reason code
Referenced by xta_transaction_new().
static struct sttsrv_config_s* client_config_get_sttsrv (const client_config_coll_t * ccc) static
Retrieve a reference to the current transaction manager properties
Parameters
ccc IN configuration reference
Returns
a pointer to the current transaction manager
Definition at line 302 of file client_config.h.
References client_config_coll_s::actconf, and actual_config_s::sttsrv.
int client_config_job (client_config_coll_t * ccc, int fd)
Perform an extra configuration step can not be performed when client_config is called
Parameters
ccc IN/OUT the object that contains the client configuration
fd IN the file descriptor associated to the server connected socket
Returns
a standardized return code
Referenced by xta_transaction_new().
int client_config_load_all_switch_files (client_config_coll_t * ccc)
Load all the configured switch files
Parameters
[in,out] ccc : configuration object reference
Returns
a standardized return code
int client_config_load_switch_file (struct act_rsrmgr_config_s * act_rsrmgr, int dynamically_defined)
Load the switch file related to a Resource Manager
Parameters
[in,out] act_rsrmgr : properties of a resource manager
[in] dynamically_defined : TRUE if the configuration has been dynamically defined by the Application Program using XTA interface; FALSE if the configuration has been statically defined inside the lixac.conf file
Returns
a reason code
Referenced by xta_native_xa_resource_init().
int client_config_rsrmgr_dup (const struct act_rsrmgr_config_s * arc, struct rsrmgr_config_s * rsrmgr, struct act_rsrmgr_config_s * act_rsrmgr)
Duplicate all the allocated objects connected to an ACTual ReSouRceManaGeR config struct
Parameters
[in] arc : the object that must be duplicated
[out] rsrmgr : the pointer to a pre-allocated space that will be used to store the duplicate of the resource manager config referenced by the first argument (arc). Use NULL if it should not be duplicated
[out] act_rsrmgr : the pointer to a pre-allocated space that will be used to store the duplicate of the actual resource manager config referenced by the first argument (arc). Use NULL if it should not be duplicated
Returns
a reason code
Referenced by xta_transaction_enlist_resource().
gchar* client_config_tostring_rsrmgr (const struct act_rsrmgr_config_s * arc)
Serialize the configuration of an actual resource manager to a string
Parameters
[in] arc : actual resource manager config
Returns
a string that must be freed with g_free() after usage
Referenced by xta_transaction_redigest().
int client_config_unload_all_switch_files (client_config_coll_t * ccc)
Unload the configured switch file for all the resource managers
Parameters
[in,out] ccc : configuration object reference
Returns
a standardized return code
int client_config_unload_switch_file (struct act_rsrmgr_config_s * act_rsrmgr)
Unload the switch file related to a Resource Manager
Parameters
[in,out] act_rsrmgr : properties of a resource manager
Returns
a reason code
Referenced by xta_native_xa_resource_clean().
int client_config_validate (client_config_coll_t * ccc)
Validate configuration: fix the transaction and resource managers
Parameters
ccc IN/OUT the object will contain the client configuration
Returns
a standardized return code
int client_parse (struct client_config_coll_s * ccc, xmlNode * a_node)
Parse the configuration tree
Parameters
ccc OUT server configuration structure
a_node IN the current subtree must be parsed
Returns
a standardized return code
int client_parse_profile (struct client_config_coll_s * ccc, xmlNode * a_node)
Parse a "profile" node tree
Parameters
ccc OUT server configuration structure
a_node IN the current subtree must be parsed
Returns
a standardized return code
int client_parse_profile_rsrmgrs (struct client_config_coll_s * ccc, xmlNode * a_node, GArray * rsrmgrs)
Parse a "rsrmgrs" node inside a "profile" node tree
Parameters
ccc OUT server configuration structure
a_node IN the current subtree must be parsed
rsrmgrs IN/OUT the array with all the resource managers defined for a profile
Returns
a standardized return code
int client_parse_profile_sttsrvs (struct client_config_coll_s * ccc, xmlNode * a_node, GArray * sttsrvs)
Parse a "sttsrvs" node inside a "profile" node tree
Parameters
ccc OUT server configuration structure
a_node IN the current subtree must be parsed
sttsrvs IN/OUT the array with all the transaction managers defined for a profile
Returns
a standardized return code
int client_parse_profiles (struct client_config_coll_s * ccc, xmlNode * a_node)
Parse a "profiles" node tree
Parameters
ccc OUT server configuration structure
a_node IN the current subtree must be parsed
Returns
a standardized return code
int client_parse_rsrmgr (struct client_config_coll_s * ccc, xmlNode * a_node)
Parse a "rsrmgr" node tree
Parameters
ccc OUT server configuration structure
a_node IN the current subtree must be parsed
Returns
a standardized return code
int client_parse_rsrmgrs (struct client_config_coll_s * ccc, xmlNode * a_node)
Parse a "rsrmgrs" node tree
Parameters
ccc OUT server configuration structure
a_node IN the current subtree must be parsed
Returns
a standardized return code
int client_parse_sttsrv (struct client_config_coll_s * ccc, xmlNode * a_node)
Parse a "sttsrv" node tree
Parameters
ccc OUT server configuration structure
a_node IN the current subtree must be parsed
Returns
a standardized return code
int client_parse_sttsrvs (struct client_config_coll_s * ccc, xmlNode * a_node)
Parse a "sttsrvs" node tree
Parameters
ccc OUT server configuration structure
a_node IN the current subtree must be parsed
Returns
a standardized return code
int client_unconfig (client_config_coll_t * ccc, int global_config)
Unload configuration and release memory
Parameters
[out] ccc : the object that contains the client configuration
[in] global_config : TRUE if "ccc" is a global static object (just one for all the threads of the process) , FALSE if "ccc" is a local dynamic object (every thread has its own). TX API uses a global static config shared by all the threads, XTA API uses a local dynamic object for every thread.
Returns
a reason code
Referenced by xta_transaction_delete(), and xta_transaction_new().
Copyright © 2009-2018, Christian Ferrari tiian@users.sourceforge.net