var files =
[
    [ "client_config.h", "client__config_8h.html", "client__config_8h" ],
    [ "lixa_config.h", "lixa__config_8h.html", "lixa__config_8h" ],
    [ "lixa_errors.h", "lixa__errors_8h.html", "lixa__errors_8h" ],
    [ "lixa_iface.h", "lixa__iface_8h.html", "lixa__iface_8h" ],
    [ "xa.h", "xa_8h.html", "xa_8h" ],
    [ "xta.h", "xta_8h.html", "xta_8h" ],
    [ "xta_acquired_xa_resource.c", "xta__acquired__xa__resource_8c.html", "xta__acquired__xa__resource_8c" ],
    [ "xta_acquired_xa_resource.h", "xta__acquired__xa__resource_8h.html", "xta__acquired__xa__resource_8h" ],
    [ "xta_errors.c", "xta__errors_8c.html", "xta__errors_8c" ],
    [ "xta_errors.h", "xta__errors_8h.html", "xta__errors_8h" ],
    [ "xta_iface.h", "xta__iface_8h.html", "xta__iface_8h" ],
    [ "xta_init.c", "xta__init_8c.html", "xta__init_8c" ],
    [ "xta_init.h", "xta__init_8h.html", "xta__init_8h" ],
    [ "xta_mysql_xa_resource.c", "xta__mysql__xa__resource_8c.html", "xta__mysql__xa__resource_8c" ],
    [ "xta_mysql_xa_resource.h", "xta__mysql__xa__resource_8h.html", "xta__mysql__xa__resource_8h" ],
    [ "xta_native_xa_resource.c", "xta__native__xa__resource_8c.html", "xta__native__xa__resource_8c" ],
    [ "xta_native_xa_resource.h", "xta__native__xa__resource_8h.html", "xta__native__xa__resource_8h" ],
    [ "xta_postgresql_xa_resource.c", "xta__postgresql__xa__resource_8c.html", "xta__postgresql__xa__resource_8c" ],
    [ "xta_postgresql_xa_resource.h", "xta__postgresql__xa__resource_8h.html", "xta__postgresql__xa__resource_8h" ],
    [ "xta_transaction.c", "xta__transaction_8c.html", "xta__transaction_8c" ],
    [ "xta_transaction.h", "xta__transaction_8h.html", "xta__transaction_8h" ],
    [ "xta_transaction_manager.c", "xta__transaction__manager_8c.html", "xta__transaction__manager_8c" ],
    [ "xta_transaction_manager.h", "xta__transaction__manager_8h.html", "xta__transaction__manager_8h" ],
    [ "xta_xa_resource.c", "xta__xa__resource_8c.html", "xta__xa__resource_8c" ],
    [ "xta_xa_resource.h", "xta__xa__resource_8h.html", "xta__xa__resource_8h" ],
    [ "xta_xid.c", "xta__xid_8c.html", "xta__xid_8c" ],
    [ "xta_xid.h", "xta__xid_8h.html", "xta__xid_8h" ]
];