XTA: XA Transaction API (LIXA: Free/Open Source Software XA Transaction Manager)
xta_transaction_manager.h File Reference
#include "lixa_trace.h"
#include "client_status.h"
#include "xta_transaction.h"
#include "xta_acquired_xa_resource.h"
Data Structures
struct xta_transaction_manager_s
Macros
#define LIXA_TRACE_MODULE LIXA_TRACE_MOD_XTA
Typedefs
typedef client_config_coll_t xta_transaction_manager_config_t
typedef struct
xta_transaction_manager_s xta_transaction_manager_t
Functions
xta_transaction_t * xta_transaction_manager_create_transaction (xta_transaction_manager_t *this)
void xta_transaction_manager_delete (xta_transaction_manager_t *this)
static
xta_transaction_manager_config_t * xta_transaction_manager_get_config (void)
xta_transaction_manager_t * xta_transaction_manager_new (void)
Macro Definition Documentation
#define LIXA_TRACE_MODULE LIXA_TRACE_MOD_XTA
Definition at line 40 of file xta_transaction_manager.h.
Typedef Documentation
typedef client_config_coll_t xta_transaction_manager_config_t
This type is just a redefinition of the legacy LIXA type "client_config_coll_t" to avoid a type with a "strange name" in the API
Definition at line 48 of file xta_transaction_manager.h.
typedef struct xta_transaction_manager_s xta_transaction_manager_t
XTA Transaction Manager data type
Function Documentation
xta_transaction_t* xta_transaction_manager_create_transaction (xta_transaction_manager_t * this)
Create a new XA Transaction object, associate it with the current process/thread and returns it to the caller. In the event that the caller thread has already created an XA Transaction, the previously created XA Transaction object is returned
Parameters
[in,out] this : transaction manager object
Returns
the pointer to an XTA Transaction object
Definition at line 121 of file xta_transaction_manager.c.
References LIXA_RC_G_HASH_TABLE_NEW_ERROR, LIXA_RC_INTERNAL_ERROR, LIXA_RC_NULL_OBJECT, LIXA_RC_OK, xta_transaction_delete(), and xta_transaction_new().
void xta_transaction_manager_delete (xta_transaction_manager_t * this)
Delete a Transaction Manager object
Parameters
[in] this : transaction manager to delete
Definition at line 84 of file xta_transaction_manager.c.
References LIXA_RC_INTERNAL_ERROR, and LIXA_RC_OK.
static xta_transaction_manager_config_t* xta_transaction_manager_get_config (void) inline static
Get the legacy LIXA object that contains the static global configurations for all the statically defined Resource Managers. This method must be intended as STATIC because it does not access the object state.
Returns
the pointer to the Transaction Manager configuration object
Definition at line 102 of file xta_transaction_manager.h.
xta_transaction_manager_t* xta_transaction_manager_new (void)
Create a new Transaction Manager object
Returns
a new transaction manager object or NULL in the event of an error occurred
Definition at line 43 of file xta_transaction_manager.c.
References client_config(), LIXA_RC_G_TRY_MALLOC_ERROR, LIXA_RC_INTERNAL_ERROR, and LIXA_RC_OK.
Copyright © 2009-2018, Christian Ferrari tiian@users.sourceforge.net