XTA: XA Transaction API (LIXA: Free/Open Source Software XA Transaction Manager)
xta_transaction_manager.c File Reference
#include "config.h"
#include "lixa_errors.h"
#include "lixa_trace.h"
#include "xta_transaction_manager.h"
Macros
#define LIXA_TRACE_MODULE LIXA_TRACE_MOD_XTA
Functions
int xta_transaction_manager_branch (xta_transaction_manager_t *transaction_manager, const xta_xid_t *xid)
xta_transaction_t * xta_transaction_manager_create_transaction (xta_transaction_manager_t *this)
void xta_transaction_manager_delete (xta_transaction_manager_t *this)
xta_transaction_manager_t * xta_transaction_manager_new (void)
Macro Definition Documentation
#define LIXA_TRACE_MODULE LIXA_TRACE_MOD_XTA
Definition at line 39 of file xta_transaction_manager.c.
Function Documentation
int xta_transaction_manager_branch (xta_transaction_manager_t * transaction_manager, const xta_xid_t * xid)
Definition at line 204 of file xta_transaction_manager.c.
References LIXA_RC_INTERNAL_ERROR, and LIXA_RC_OK.
xta_transaction_t* xta_transaction_manager_create_transaction (xta_transaction_manager_t * this)
Create a new XA Transaction object, associate it with the current process/thread and returns it to the caller. In the event that the caller thread has already created an XA Transaction, the previously created XA Transaction object is returned
Parameters
[in,out] this : transaction manager object
Returns
the pointer to an XTA Transaction object
Definition at line 121 of file xta_transaction_manager.c.
References LIXA_RC_G_HASH_TABLE_NEW_ERROR, LIXA_RC_INTERNAL_ERROR, LIXA_RC_NULL_OBJECT, LIXA_RC_OK, xta_transaction_delete(), and xta_transaction_new().
void xta_transaction_manager_delete (xta_transaction_manager_t * this)
Delete a Transaction Manager object
Parameters
[in] this : transaction manager to delete
Definition at line 84 of file xta_transaction_manager.c.
References LIXA_RC_INTERNAL_ERROR, and LIXA_RC_OK.
xta_transaction_manager_t* xta_transaction_manager_new (void)
Create a new Transaction Manager object
Returns
a new transaction manager object or NULL in the event of an error occurred
Definition at line 43 of file xta_transaction_manager.c.
References client_config(), LIXA_RC_G_TRY_MALLOC_ERROR, LIXA_RC_INTERNAL_ERROR, and LIXA_RC_OK.
Copyright © 2009-2018, Christian Ferrari tiian@users.sourceforge.net