XTA: XA Transaction API (LIXA: Free/Open Source Software XA Transaction Manager)
xta_acquired_xa_resource.h File Reference
#include <config.h>
#include "lixa_trace.h"
#include "xta_xa_resource.h"
#include "xta_iface.h"
#include "xa.h"
Data Structures
struct xta_acquired_xa_resource_t
Macros
#define LIXA_TRACE_MODULE LIXA_TRACE_MOD_XTA
Functions
void xta_acquired_xa_resource_clean (xta_acquired_xa_resource_t *this)
int xta_acquired_xa_resource_init (xta_acquired_xa_resource_t *this, const struct xta_iface_s *iface, const char *name, const char *open_info)
Macro Definition Documentation
#define LIXA_TRACE_MODULE LIXA_TRACE_MOD_XTA
Definition at line 49 of file xta_acquired_xa_resource.h.
Function Documentation
void xta_acquired_xa_resource_clean (xta_acquired_xa_resource_t * this)
Clean the common properties of Acquired XA Resources; this function must be called after xta_acquired_xa_resource_init during object deletion to avoid memory leaks
Parameters
[in,out] this : Acquired XA Resource object
Definition at line 132 of file xta_acquired_xa_resource.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_NULL_OBJECT, and LIXA_RC_OK.
Referenced by xta_mysql_xa_resource_clean(), and xta_postgresql_xa_resource_clean().
int xta_acquired_xa_resource_init (xta_acquired_xa_resource_t * this, const struct xta_iface_s * iface, const char * name, const char * open_info)
Initialize the common properties of Acquired XA Resources
Parameters
[in,out] this : Acquired XA Resource object
[in] iface : interface with XA function pointers
[in] name : unique identifier of the resource
[in] open_info : unique description of the connection properties like network name/IP address, port, user/schema, etc. Only the first MAXINFOSIZE characters will be kept.
Returns
a reason code
Definition at line 43 of file xta_acquired_xa_resource.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_INVALID_OPTION, LIXA_RC_NULL_OBJECT, LIXA_RC_OBJ_CORRUPTED, LIXA_RC_OK, LIXA_RC_XML_STRDUP_ERROR, MAXINFOSIZE, and xta_xa_resource_init().
Referenced by xta_mysql_xa_resource_init(), and xta_postgresql_xa_resource_init().
Copyright © 2009-2018, Christian Ferrari tiian@users.sourceforge.net