XTA: XA Transaction API (LIXA: Free/Open Source Software XA Transaction Manager)
xta_postgresql_xa_resource.c File Reference
#include <config.h>
#include "lixa_errors.h"
#include "lixa_trace.h"
#include "liblixapq.h"
#include "xta_postgresql_xa_resource.h"
Macros
#define LIXA_TRACE_MODULE LIXA_TRACE_MOD_XTA
Functions
int xta_postgresql_xa_close (xta_xa_resource_t *context, char *xa_info, int rmid, long flags)
int xta_postgresql_xa_commit (xta_xa_resource_t *context, const XID *xid, int rmid, long flags)
int xta_postgresql_xa_end (xta_xa_resource_t *context, const XID *xid, int rmid, long flags)
int xta_postgresql_xa_forget (xta_xa_resource_t *context, const XID *xid, int rmid, long flags)
int xta_postgresql_xa_open (xta_xa_resource_t *context, char *xa_info, int rmid, long flags)
int xta_postgresql_xa_prepare (xta_xa_resource_t *context, const XID *xid, int rmid, long flags)
int xta_postgresql_xa_recover (xta_xa_resource_t *context, XID *xids, long count, int rmid, long flags)
void xta_postgresql_xa_resource_clean (xta_postgresql_xa_resource_t *this)
void xta_postgresql_xa_resource_delete (xta_postgresql_xa_resource_t *this)
int xta_postgresql_xa_resource_init (xta_postgresql_xa_resource_t *this, PGconn *connection, const char *name, const char *open_info)
xta_postgresql_xa_resource_t * xta_postgresql_xa_resource_new (PGconn *connection, const char *name, const char *open_info)
int xta_postgresql_xa_rollback (xta_xa_resource_t *context, const XID *xid, int rmid, long flags)
int xta_postgresql_xa_start (xta_xa_resource_t *context, const XID *xid, int rmid, long flags)
Variables
static const struct xta_iface_s xta_postgresql_iface
Macro Definition Documentation
#define LIXA_TRACE_MODULE LIXA_TRACE_MOD_XTA
Definition at line 40 of file xta_postgresql_xa_resource.c.
Function Documentation
int xta_postgresql_xa_close (xta_xa_resource_t * context, char * xa_info, int rmid, long flags)
Close a Postgresql resource manager
Parameters
[in,out] context : XTA resource context
[in] xa_info : null-terminated character string that may contain instance-specific information for the resource manager
[in] rmid : an integer assigned by the transaction manager, uniquely identifies the called resource manager instance within the thread of control
[in] flags : TMNOFLAGS, future usage only
Returns
a XA return code
Definition at line 250 of file xta_postgresql_xa_resource.c.
References XA_OK, and XAER_RMERR.
int xta_postgresql_xa_commit (xta_xa_resource_t * context, const XID * xid, int rmid, long flags)
Commit work done on behalf of a transaction branch
Parameters
[in,out] context : XTA resource context
[in] xid transaction identifier, XA spec
[in] rmid : an integer assigned by the transaction manager, uniquely identifies the called resource manager instance within the thread of control
[in] flags : TMONEPHASE or TMNOFLAGS
Returns
a XA return code
Definition at line 443 of file xta_postgresql_xa_resource.c.
References XA_OK, and XAER_RMERR.
int xta_postgresql_xa_end (xta_xa_resource_t * context, const XID * xid, int rmid, long flags)
End work performed on behalf of a transaction branch
Parameters
[in,out] context XTA resource context
[in] xid transaction identifier, XA spec
[in] rmid an integer assigned by the transaction manager, uniquely identifies the called resource manager instance within the thread of control
[in] flags only TMSUCCESS and TMFAIL can be passed to a Postgresql resource
Returns
a XA return code
Definition at line 328 of file xta_postgresql_xa_resource.c.
References XA_OK, and XAER_RMERR.
int xta_postgresql_xa_forget (xta_xa_resource_t * context, const XID * xid, int rmid, long flags)
Forget about a heuristically completed transaction branch
Parameters
[in,out] context : XTA resource context
[in] xid transaction identifier, XA spec
[in] rmid : an integer assigned by the transaction manager, uniquely identifies the called resource manager instance within the thread of control
[in] flags : TMNOFLAGS, future usage only
Returns
a XA return code
Definition at line 519 of file xta_postgresql_xa_resource.c.
References XA_OK, and XAER_RMERR.
int xta_postgresql_xa_open (xta_xa_resource_t * context, char * xa_info, int rmid, long flags)
Open a PostgreSQL resource manager
Parameters
[in,out] context : XTA resource context
[in] xa_info : null-terminated character string that may contain instance-specific information for the resource manager
[in] rmid : an integer assigned by the transaction manager, uniquely identifies the called resource manager instance within the thread of control
[in] flags : TMNOFLAGS, future usage only
Returns
a XA return code
Definition at line 205 of file xta_postgresql_xa_resource.c.
References XA_OK, and XAER_RMERR.
int xta_postgresql_xa_prepare (xta_xa_resource_t * context, const XID * xid, int rmid, long flags)
Prepare to commit work done on behalf of a transaction branch
Parameters
[in,out] context : XTA resource context
[in] xid transaction identifier, XA spec
[in] rmid : an integer assigned by the transaction manager, uniquely identifies the called resource manager instance within the thread of control
[in] flags : TMNOFLAGS, future usage only
Returns
a XA return code
Definition at line 405 of file xta_postgresql_xa_resource.c.
References XA_OK, and XAER_RMERR.
int xta_postgresql_xa_recover (xta_xa_resource_t * context, XID * xids, long count, int rmid, long flags)
Obtain a list of prepared transaction branches from a resource manager
Parameters
[in,out] context : XTA resource context
[in] xids : an array into which the resource manager places XIDs for list of transaction branches that are currently in a prepared or heuristically completed state
[in] count : the maximum number of XIDs that fit into that array
[in] rmid : an integer assigned by the transaction manager, uniquely identifies the called resource manager instance within the thread of control
[in] flags : TMSTARTRSCAN, TMENDRSCAN, TMNOFLAGS
Returns
a XA return code
Definition at line 481 of file xta_postgresql_xa_resource.c.
References XA_OK, and XAER_RMERR.
void xta_postgresql_xa_resource_clean (xta_postgresql_xa_resource_t * this)
Clean the properties of a PostgreSQL XA Resource; this function must be called after xta_postgresql_xa_resource_init during object deletion to avoid memory leaks
Parameters
[in,out] this : PostgreSQL XA Resource object
Definition at line 175 of file xta_postgresql_xa_resource.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_OK, and xta_acquired_xa_resource_clean().
Referenced by xta_postgresql_xa_resource_delete().
void xta_postgresql_xa_resource_delete (xta_postgresql_xa_resource_t * this)
Delete an object that represent a PostgreSQL XA Resource
Parameters
[in] this : PostgreSQL XA Resource
Definition at line 103 of file xta_postgresql_xa_resource.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_OK, and xta_postgresql_xa_resource_clean().
int xta_postgresql_xa_resource_init (xta_postgresql_xa_resource_t * this, PGconn * connection, const char * name, const char * open_info)
Initialize the propeties of a PostgreSQL XA resource
Parameters
[in,out] this : PostgreSQL XA Resource object
[in] connection : to PostgreSQL already opened by the application program
[in] name : unique identifier of the resource
[in] open_info : unique description of the connection properties like network name/IP address, port, user/schema, etc. Only the first MAXINFOSIZE characters will be kept.
Returns
a new object or NULL in the event of error
Definition at line 132 of file xta_postgresql_xa_resource.c.
References lixa_iface_set_xta(), LIXA_RC_INTERNAL_ERROR, LIXA_RC_OK, and xta_acquired_xa_resource_init().
Referenced by xta_postgresql_xa_resource_new().
xta_postgresql_xa_resource_t* xta_postgresql_xa_resource_new (PGconn * connection, const char * name, const char * open_info)
Create a new object to represent a PostgreSQL XA resource
Parameters
[in] connection to PostgreSQL already opened by the application program
[in] name : unique identifier of the resource
[in] open_info : unique description of the connection properties like network name/IP address, port, user/schema, etc. Only the first MAXINFOSIZE characters will be kept.
Returns
a new object or NULL in the event of error
Definition at line 61 of file xta_postgresql_xa_resource.c.
References LIXA_RC_G_TRY_MALLOC_ERROR, LIXA_RC_INTERNAL_ERROR, LIXA_RC_OK, and xta_postgresql_xa_resource_init().
int xta_postgresql_xa_rollback (xta_xa_resource_t * context, const XID * xid, int rmid, long flags)
Roll back work done on behalf of a transaction branch
Parameters
[in,out] context : XTA resource context
[in] xid transaction identifier, XA spec
[in] rmid : an integer assigned by the transaction manager, uniquely identifies the called resource manager instance within the thread of control
[in] flags : TMNOFLAGS, future usage only
Returns
a XA return code
Definition at line 367 of file xta_postgresql_xa_resource.c.
References XA_OK, and XAER_RMERR.
int xta_postgresql_xa_start (xta_xa_resource_t * context, const XID * xid, int rmid, long flags)
Start work on behalf of a transaction branch
Parameters
[in,out] context XTA resource context
[in] xid transaction identifier, XA spec
[in] rmid an integer assigned by the transaction manager, uniquely identifies the called resource manager instance within the thread of control
[in] flags only TMNOFLAGS can be passed to a Postgresql resource
Returns
a XA return code
Definition at line 290 of file xta_postgresql_xa_resource.c.
References XA_OK, and XAER_RMERR.
Variable Documentation
const struct xta_iface_s xta_postgresql_iface static
Initial value:
= {
    "XTA PostgreSQL",
    TMNOFLAGS,
    0,
    xta_postgresql_xa_open,
    xta_postgresql_xa_close,
    xta_postgresql_xa_start,
    xta_postgresql_xa_end,
    xta_postgresql_xa_rollback,
    xta_postgresql_xa_prepare,
    xta_postgresql_xa_commit,
    xta_postgresql_xa_recover,
    xta_postgresql_xa_forget
}
Definition at line 44 of file xta_postgresql_xa_resource.c.
Copyright © 2009-2018, Christian Ferrari tiian@users.sourceforge.net