XTA: XA Transaction API (LIXA: Free/Open Source Software XA Transaction Manager)
xta_transaction.h File Reference
#include "lixa_trace.h"
#include "client_status.h"
#include "xta_xa_resource.h"
Data Structures
struct xta_transaction_s
Macros
#define LIXA_TRACE_MODULE LIXA_TRACE_MOD_XTA
Typedefs
typedef client_config_coll_t xta_transaction_config_t
typedef struct xta_transaction_s xta_transaction_t
typedef struct xta_xa_resource_s xta_xa_resource_t
Functions
int xta_transaction_branch (xta_transaction_t *this, const char *xid_string)
int xta_transaction_close (xta_transaction_t *this)
int xta_transaction_commit (xta_transaction_t *this, int non_block)
void xta_transaction_delete (xta_transaction_t *this)
int xta_transaction_enlist_resource (xta_transaction_t *this, xta_xa_resource_t *xa_res)
xta_transaction_config_t * xta_transaction_get_config (xta_transaction_t *this)
const xta_xid_t * xta_transaction_get_xid (const xta_transaction_t *this)
xta_transaction_t * xta_transaction_new (void)
int xta_transaction_open (xta_transaction_t *this)
int xta_transaction_redigest (xta_transaction_t *this, const xta_xa_resource_config_t *xrc)
int xta_transaction_resume (xta_transaction_t *this, const char *xid_string, long flags)
int xta_transaction_rollback (xta_transaction_t *this)
int xta_transaction_start (xta_transaction_t *this, int multiple_branches)
int xta_transaction_suspend (xta_transaction_t *this, long flags)
Macro Definition Documentation
#define LIXA_TRACE_MODULE LIXA_TRACE_MOD_XTA
Definition at line 39 of file xta_transaction.h.
Typedef Documentation
typedef client_config_coll_t xta_transaction_config_t
This type is just a redefinition of the legacy LIXA type client_config_coll_t to avoid a type with a "strange name" in the API
Definition at line 47 of file xta_transaction.h.
typedef struct xta_transaction_s xta_transaction_t
XTA Transaction data type
typedef struct xta_xa_resource_s xta_xa_resource_t
Definition at line 56 of file xta_transaction.h.
Function Documentation
int xta_transaction_branch (xta_transaction_t * this, const char * xid_string)
Create a new branch of the transaction represented by xid in this transaction object; the global transaction has been previously started
Parameters
[in,out] this : transaction object
[in] xid_string serialized identifier of the global transaction that must be branched
Returns
a reason code
Definition at line 1172 of file xta_transaction.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_INVALID_STATUS, LIXA_RC_MALFORMED_XID, LIXA_RC_NO_SUPERIOR_BRANCH, LIXA_RC_NON_BRANCHABLE_TX, LIXA_RC_NULL_OBJECT, LIXA_RC_OK, TMXTABRANCH, xta_xid_branch_qualifier_is_multibranch(), xta_xid_get_xa_xid(), and xta_xid_new_from_XID().
int xta_transaction_close (xta_transaction_t * this)
Shut down the XA Resource Managers and the XA Transaction Manager after transactional Unit of Work completion. From the XA specification point of view, it calls xa_close (for the Native XA Resource Managers)
Parameters
[in,out] this : transaction object
Returns
a reason code
Definition at line 497 of file xta_transaction.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_INVALID_STATUS, LIXA_RC_NULL_OBJECT, LIXA_RC_OK, and LIXA_RC_PROTOCOL_ERROR.
int xta_transaction_commit (xta_transaction_t * this, int non_block)
Commit the transaction represented by this transaction object
Parameters
[in,out] this : transaction object
[in] non_block boolean value:
TRUE = xa_prepare will not block the caller
FALSE = xa_prepare will block the caller
the option is used only for multiple branch transactions
Returns
a reason code
Definition at line 634 of file xta_transaction.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_INVALID_STATUS, LIXA_RC_NULL_OBJECT, LIXA_RC_OK, LIXA_RC_OTHER_BRANCH_ERROR, LIXA_RC_TX_HAZARD, LIXA_RC_TX_MIXED, LIXA_RC_TX_ROLLBACK, LIXA_RC_WOULD_BLOCK, TMSUCCESS, xta_xid_branch_qualifier_is_multibranch(), xta_xid_get_xa_xid(), and xta_xid_reset().
void xta_transaction_delete (xta_transaction_t * this)
Delete a Transaction object
Parameters
[in] this : transaction object to delete
Definition at line 149 of file xta_transaction.c.
References client_unconfig(), LIXA_RC_INTERNAL_ERROR, LIXA_RC_OK, and xta_xid_delete().
Referenced by xta_transaction_manager_create_transaction().
int xta_transaction_enlist_resource (xta_transaction_t * this, xta_xa_resource_t * xa_res)
Enlist the resource specified with the Transaction associated with the Transaction object
Parameters
[in,out] this : transaction object
[in] xa_res : resource to associate
Returns
a reason code
Definition at line 224 of file xta_transaction.c.
References client_config_append_rsrmgr(), client_config_rsrmgr_dup(), LIXA_RC_G_TRY_MALLOC_ERROR, LIXA_RC_INTERNAL_ERROR, LIXA_RC_INVALID_STATUS, LIXA_RC_NULL_OBJECT, LIXA_RC_OK, xta_transaction_redigest(), xta_xa_resource_enlisted(), xta_xa_resource_get_config(), and xta_xa_resource_is_dynamic().
xta_transaction_config_t* xta_transaction_get_config (xta_transaction_t * this)
Get the legacy LIXA object that contains the configurations for all the define Resource Managers
Parameters
[in] this : Transaction object
Returns
the pointer to the Transaction configuration object
Definition at line 191 of file xta_transaction.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_NULL_OBJECT, and LIXA_RC_OK.
const xta_xid_t* xta_transaction_get_xid (const xta_transaction_t * this)
Get the Xid associated with the Transaction object
Parameters
[in] this : transaction object
Returns
a reference to the Transaction Identifier
Definition at line 1298 of file xta_transaction.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_NULL_OBJECT, and LIXA_RC_OK.
xta_transaction_t* xta_transaction_new (void)
Create a new Transaction object
Returns
a new transaction object or NULL in the event of an error occurred
Definition at line 53 of file xta_transaction.c.
References client_config_display(), client_config_dup(), client_config_job(), client_unconfig(), LIXA_RC_G_TRY_MALLOC_ERROR, LIXA_RC_INTERNAL_ERROR, and LIXA_RC_OK.
Referenced by xta_transaction_manager_create_transaction().
int xta_transaction_open (xta_transaction_t * this)
Prepare the XA Resource Managers and the XA Transaction Manager for a new transactional Unit of Work. From the XA specification point of view, it calls xa_open (for the Native XA Resource Managers)
Parameters
[in,out] this : transaction object
Returns
a reason code
Definition at line 433 of file xta_transaction.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_INVALID_STATUS, LIXA_RC_NULL_OBJECT, and LIXA_RC_OK.
int xta_transaction_redigest (xta_transaction_t * this, const xta_xa_resource_config_t * xrc)
When a resource registers dynamically the digest must be updated because the configuration has been altered. This must be considered a PRIVATE method and should not be used by the Application Program.
Parameters
[in,out] this : transaction object
[in] xrc : XA resource configuration (LIXA legacy structure)
Returns
a reason code
Definition at line 333 of file xta_transaction.c.
References client_config_tostring_rsrmgr(), lixa_job_get_raw(), lixa_job_reset(), lixa_job_set_config_digest(), lixa_job_set_source_ip(), LIXA_RC_G_CHECKSUM_GET_STRING_ERROR, LIXA_RC_G_CHECKSUM_NEW_ERROR, LIXA_RC_INTERNAL_ERROR, LIXA_RC_NULL_OBJECT, LIXA_RC_OK, and MD5_DIGEST_LENGTH.
Referenced by xta_transaction_enlist_resource().
int xta_transaction_resume (xta_transaction_t * this, const char * xid_string, long flags)
Resume the transaction represented by xid in this transaction object; the transaction has been previously suspended with xta_transaction_suspend
Parameters
[in,out] this transaction object
[in] xid_string serialized identifier of the transaction that must be resumed (see xta_xid_to_string)
[in] flags can be TMRESUME if the transaction has been suspended using TMMIGRATE or TMJOIN if the transaction has been suspended using TMNOFLAGS
Returns
a reason code
Definition at line 1080 of file xta_transaction.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_INVALID_OPTION, LIXA_RC_INVALID_STATUS, LIXA_RC_NULL_OBJECT, LIXA_RC_OK, LIXA_RC_PROTOCOL_ERROR, TMJOIN, TMRESUME, xta_xid_get_xa_xid(), and xta_xid_new_from_string().
int xta_transaction_rollback (xta_transaction_t * this)
Rollback the transaction represented by this transaction object
Parameters
[in,out] this : transaction object
Returns
a reason code
Definition at line 883 of file xta_transaction.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_INVALID_STATUS, LIXA_RC_NULL_OBJECT, LIXA_RC_OK, LIXA_RC_TX_HAZARD, LIXA_RC_TX_MIXED, TMSUCCESS, xta_xid_get_xa_xid(), and xta_xid_reset().
int xta_transaction_start (xta_transaction_t * this, int multiple_branches)
Start a new XA Transaction. From the XA specification point of view, it calls xa_start (for the Native XA Resource Managers)
Parameters
[in,out] this : transaction object
[in] multiple_branches : boolean value:
TRUE = the created transaction will span more applications, xta_transaction_branch will be called subsequently
FALSE = the created transaction will not span more applications and xta_transaction_branch will not be called for this transaction
Returns
a reason code
Definition at line 566 of file xta_transaction.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_INVALID_STATUS, LIXA_RC_NULL_OBJECT, LIXA_RC_OK, TMNOFLAGS, xta_xid_get_xa_xid(), and xta_xid_new().
int xta_transaction_suspend (xta_transaction_t * this, long flags)
Suspend the transaction represented by this transaction object; the transaction can be resumed with xta_transaction_resume at a later time
Parameters
[in,out] this : transaction object
[in] flags can be TMMIGRATE if the Resource Manager supports transaction migration and TMNOFLAGS otherwise
Returns
a reason code
Definition at line 999 of file xta_transaction.c.
References LIXA_RC_INTERNAL_ERROR, LIXA_RC_INVALID_OPTION, LIXA_RC_INVALID_STATUS, LIXA_RC_NULL_OBJECT, LIXA_RC_OK, LIXA_RC_PROTOCOL_ERROR, TMMIGRATE, TMNOFLAGS, TMSUSPEND, and xta_xid_get_xa_xid().
Copyright © 2009-2018, Christian Ferrari tiian@users.sourceforge.net