libflom: FLoM (Free Lock Manager) client library
flom_errors.h File Reference
Macros
#define FLOM_ES_GENERIC_ERROR 99
#define FLOM_ES_OK 0
#define FLOM_ES_REQUESTER_CANT_WAIT 96
#define FLOM_ES_RESOURCE_BUSY 98
#define FLOM_ES_UNABLE_TO_EXECUTE_COMMAND 97
#define FLOM_RC_ACCEPT_ERROR -100
#define FLOM_RC_API_IMMUTABLE_HANDLE +11
#define FLOM_RC_API_INVALID_SEQUENCE -17
#define FLOM_RC_BIND_ERROR -101
#define FLOM_RC_BUFFER_OVERFLOW -9
#define FLOM_RC_CHDIR_ERROR -102
#define FLOM_RC_CLOSE_ERROR -103
#define FLOM_RC_CONNECT_ERROR -104
#define FLOM_RC_CONNECTION_CLOSED +8
#define FLOM_RC_CONNECTION_CLOSED_BY_SERVER -27
#define FLOM_RC_CONNECTION_REFUSED +7
#define FLOM_RC_CONTAINER_FULL -12
#define FLOM_RC_DAEMON_NOT_STARTED -2
#define FLOM_RC_ELEMENT_NAME_NOT_AVAILABLE +10
#define FLOM_RC_EXECVP_ERROR -105
#define FLOM_RC_FCNTL_ERROR -106
#define FLOM_RC_FLOCK_ERROR -107
#define FLOM_RC_FORK_ERROR -108
#define FLOM_RC_G_ARRAY_NEW_ERROR -200
#define FLOM_RC_G_BASE64_DECODE_ERROR -201
#define FLOM_RC_G_BASE64_ENCODE_ERROR -202
#define FLOM_RC_G_KEY_FILE_LOAD_FROM_FILE_ERROR -203
#define FLOM_RC_G_KEY_FILE_NEW_ERROR -204
#define FLOM_RC_G_MARKUP_PARSE_CONTEXT_NEW_ERROR -205
#define FLOM_RC_G_MARKUP_PARSE_CONTEXT_PARSE_ERROR -206
#define FLOM_RC_G_PTR_ARRAY_REMOVE_INDEX_FAST_ERROR -207
#define FLOM_RC_G_QUEUE_NEW_ERROR -208
#define FLOM_RC_G_STRDUP_ERROR -209
#define FLOM_RC_G_STRNDUP_ERROR -210
#define FLOM_RC_G_STRSPLIT_ERROR -211
#define FLOM_RC_G_THREAD_CREATE_ERROR -212
#define FLOM_RC_G_TRY_MALLOC_ERROR -213
#define FLOM_RC_G_TRY_REALLOC_ERROR -214
#define FLOM_RC_GET_FIELD_ID_ERROR -300
#define FLOM_RC_GET_OBJECT_CLASS_ERROR -301
#define FLOM_RC_GETADDRINFO_ERROR -109
#define FLOM_RC_GETIFADDRS_ERROR -110
#define FLOM_RC_GETNAMEINFO_ERROR -111
#define FLOM_RC_GETSOCKNAME_ERROR -112
#define FLOM_RC_GETSOCKOPT_ERROR -113
#define FLOM_RC_GETTIMEOFDAY_ERROR -114
#define FLOM_RC_INET_NTOP_ERROR -115
#define FLOM_RC_INTERNAL_ERROR -1
#define FLOM_RC_INVALID_AI_FAMILY_ERROR -18
#define FLOM_RC_INVALID_IP_ADDRESS -19
#define FLOM_RC_INVALID_IPV6_NETWORK_INTERFACE -20
#define FLOM_RC_INVALID_MSG_LENGTH -10
#define FLOM_RC_INVALID_OPTION -5
#define FLOM_RC_INVALID_PREFIX_SIZE -8
#define FLOM_RC_INVALID_PROPERTY_VALUE -11
#define FLOM_RC_INVALID_RESOURCE_NAME -14
#define FLOM_RC_INVALID_TIMESTAMP_FORMAT -25
#define FLOM_RC_LISTEN_ERROR -116
#define FLOM_RC_LOCALTIME_R_ERROR -117
#define FLOM_RC_LOCK_BUSY +4
#define FLOM_RC_LOCK_CANT_LOCK +3
#define FLOM_RC_LOCK_CANT_WAIT +5
#define FLOM_RC_LOCK_ENQUEUED +1
#define FLOM_RC_LOCK_IMPOSSIBLE +6
#define FLOM_RC_LOCK_WAIT_RESOURCE +2
#define FLOM_RC_MALLOC_ERROR -118
#define FLOM_RC_MSG_DESERIALIZE_ERROR -16
#define FLOM_RC_NETWORK_EVENT_ERROR -3
#define FLOM_RC_NETWORK_TIMEOUT +9
#define FLOM_RC_NEW_DIRECT_BYTE_BUFFER_ERROR -302
#define FLOM_RC_NEW_OBJ -21
#define FLOM_RC_NO_CERTIFICATE -22
#define FLOM_RC_NO_TLS_CONNECTION -24
#define FLOM_RC_NULL_OBJECT -4
#define FLOM_RC_OBJ_CORRUPTED -6
#define FLOM_RC_OK 0
#define FLOM_RC_OPEN_ERROR -119
#define FLOM_RC_OUT_OF_RANGE -7
#define FLOM_RC_PIPE_ERROR -120
#define FLOM_RC_POLL_ERROR -121
#define FLOM_RC_PROTOCOL_ERROR -13
#define FLOM_RC_PROTOCOL_LEVEL_MISMATCH -15
#define FLOM_RC_READ_ERROR -122
#define FLOM_RC_REALPATH_ERROR -123
#define FLOM_RC_RECV_ERROR -124
#define FLOM_RC_RECVFROM_ERROR -125
#define FLOM_RC_REGCOMP_ERROR -126
#define FLOM_RC_REGEXEC_ERROR -127
#define FLOM_RC_RESOURCE_INIT_ERROR -26
#define FLOM_RC_RESOURCE_IS_NOT_TRANSACTIONAL +12
#define FLOM_RC_SEND_ERROR -128
#define FLOM_RC_SENDTO_ERROR -129
#define FLOM_RC_SETSID_ERROR -130
#define FLOM_RC_SETSOCKOPT_ERROR -131
#define FLOM_RC_SIGACTION_ERROR -132
#define FLOM_RC_SIGNAL_ERROR -133
#define FLOM_RC_SNPRINTF_ERROR -135
#define FLOM_RC_SOCKET_ERROR -134
#define FLOM_RC_SSL_ACCEPT_ERROR -405
#define FLOM_RC_SSL_CONNECT_ERROR -406
#define FLOM_RC_SSL_CTX_CHECK_PRIVATE_KEY_ERROR -400
#define FLOM_RC_SSL_CTX_LOAD_VERIFY_LOCATIONS_ERROR -401
#define FLOM_RC_SSL_CTX_NEW_ERROR -402
#define FLOM_RC_SSL_CTX_USE_CERTIFICATE_FILE_ERROR -403
#define FLOM_RC_SSL_CTX_USE_PRIVATEKEY_FILE_ERROR -404
#define FLOM_RC_SSL_GET_VERIFY_RESULT_ERROR -407
#define FLOM_RC_SSL_NEW_ERROR -408
#define FLOM_RC_SSL_READ_ERROR -409
#define FLOM_RC_SSL_SET_EX_DATA_ERROR -410
#define FLOM_RC_SSL_SET_FD_ERROR -411
#define FLOM_RC_SSL_WRITE_ERROR -412
#define FLOM_RC_TLS_NO_VALID_METHOD -413
#define FLOM_RC_UNIQUE_ID_DOES_NOT_MATCH -23
#define FLOM_RC_UNLINK_ERROR -136
#define FLOM_RC_WAIT_ERROR -137
#define FLOM_RC_WRITE_ERROR -138
Functions
const char * flom_strerror (int ret_cod)
Macro Definition Documentation
#define FLOM_ES_GENERIC_ERROR 99
Exit status when FLOM pick-up an error
Definition at line 54 of file flom_errors.h.
#define FLOM_ES_OK 0
Exit status when FLOM terminates without errors (and without executing some process)
Definition at line 59 of file flom_errors.h.
#define FLOM_ES_REQUESTER_CANT_WAIT 96
Exit status when FLOM is unable to immediately lock a resource (it could be at a later time, but not at current time)
Definition at line 41 of file flom_errors.h.
#define FLOM_ES_RESOURCE_BUSY 98
Exit status when FLOM is unable to lock a resource already locked by someone else
Definition at line 50 of file flom_errors.h.
#define FLOM_ES_UNABLE_TO_EXECUTE_COMMAND 97
Exit status when FLOM is unable to execute the command
Definition at line 45 of file flom_errors.h.
#define FLOM_RC_ACCEPT_ERROR -100
"accept" function error
Definition at line 258 of file flom_errors.h.
#define FLOM_RC_API_IMMUTABLE_HANDLE +11
The handle can not be changed at this time (probably, some API was called using an invalid sequence)
Definition at line 84 of file flom_errors.h.
#define FLOM_RC_API_INVALID_SEQUENCE -17
An API function was called using an invalid sequence
Definition at line 210 of file flom_errors.h.
#define FLOM_RC_BIND_ERROR -101
"bind" function error
Definition at line 262 of file flom_errors.h.
#define FLOM_RC_BUFFER_OVERFLOW -9
The process has been stopped to avoid a buffer overflow
Definition at line 178 of file flom_errors.h.
#define FLOM_RC_CHDIR_ERROR -102
"chdir" function error
Definition at line 266 of file flom_errors.h.
#define FLOM_RC_CLOSE_ERROR -103
"close" function error
Definition at line 270 of file flom_errors.h.
#define FLOM_RC_CONNECT_ERROR -104
"connect" function error
Definition at line 274 of file flom_errors.h.
#define FLOM_RC_CONNECTION_CLOSED +8
Peer has closed socket while expecting data
Definition at line 97 of file flom_errors.h.
#define FLOM_RC_CONNECTION_CLOSED_BY_SERVER -27
The server has unilaterally closed the connection
Definition at line 251 of file flom_errors.h.
#define FLOM_RC_CONNECTION_REFUSED +7
Peer is not ready to accept a connection
Definition at line 101 of file flom_errors.h.
#define FLOM_RC_CONTAINER_FULL -12
The container is full and can NOT store more elements
Definition at line 190 of file flom_errors.h.
#define FLOM_RC_DAEMON_NOT_STARTED -2
Flom was not able to start a new daemon and/or connect to it
Definition at line 149 of file flom_errors.h.
#define FLOM_RC_ELEMENT_NAME_NOT_AVAILABLE +10
The name of the element is not available (probably, the resource is not of type "set")
Definition at line 89 of file flom_errors.h.
#define FLOM_RC_EXECVP_ERROR -105
"execvp" function error
Definition at line 278 of file flom_errors.h.
#define FLOM_RC_FCNTL_ERROR -106
"fcntl" function error
Definition at line 282 of file flom_errors.h.
#define FLOM_RC_FLOCK_ERROR -107
"flock" function error
Definition at line 286 of file flom_errors.h.
#define FLOM_RC_FORK_ERROR -108
"fork" function error
Definition at line 290 of file flom_errors.h.
#define FLOM_RC_G_ARRAY_NEW_ERROR -200
"g_array_new" function error
Definition at line 417 of file flom_errors.h.
#define FLOM_RC_G_BASE64_DECODE_ERROR -201
"g_base64_decode" function error
Definition at line 421 of file flom_errors.h.
#define FLOM_RC_G_BASE64_ENCODE_ERROR -202
"g_base64_encode" function error
Definition at line 425 of file flom_errors.h.
#define FLOM_RC_G_KEY_FILE_LOAD_FROM_FILE_ERROR -203
"g_key_file_load_from_file" function error
Definition at line 429 of file flom_errors.h.
#define FLOM_RC_G_KEY_FILE_NEW_ERROR -204
"g_key_file_new" function error
Definition at line 433 of file flom_errors.h.
#define FLOM_RC_G_MARKUP_PARSE_CONTEXT_NEW_ERROR -205
"g_markup_parse_context_new_error" function error
Definition at line 437 of file flom_errors.h.
#define FLOM_RC_G_MARKUP_PARSE_CONTEXT_PARSE_ERROR -206
"g_markup_parse_context_parse" function error
Definition at line 441 of file flom_errors.h.
#define FLOM_RC_G_PTR_ARRAY_REMOVE_INDEX_FAST_ERROR -207
"g_ptr_array_remove_index_fast" function error
Definition at line 445 of file flom_errors.h.
#define FLOM_RC_G_QUEUE_NEW_ERROR -208
"g_queue_new" function error
Definition at line 449 of file flom_errors.h.
#define FLOM_RC_G_STRDUP_ERROR -209
"g_strdup" function error
Definition at line 453 of file flom_errors.h.
#define FLOM_RC_G_STRNDUP_ERROR -210
"g_strndup" function error
Definition at line 457 of file flom_errors.h.
#define FLOM_RC_G_STRSPLIT_ERROR -211
"g_strsplit" function error
Definition at line 461 of file flom_errors.h.
#define FLOM_RC_G_THREAD_CREATE_ERROR -212
"g_thread_create" function error
Definition at line 465 of file flom_errors.h.
#define FLOM_RC_G_TRY_MALLOC_ERROR -213
"g_try_malloc"/"g_try_malloc0" function error
Definition at line 469 of file flom_errors.h.
#define FLOM_RC_G_TRY_REALLOC_ERROR -214
"g_try_realloc" function error
Definition at line 473 of file flom_errors.h.
#define FLOM_RC_GET_FIELD_ID_ERROR -300
JNI "GetFieldID" function error
Definition at line 480 of file flom_errors.h.
#define FLOM_RC_GET_OBJECT_CLASS_ERROR -301
JNI "GetObjectClass" function error
Definition at line 484 of file flom_errors.h.
#define FLOM_RC_GETADDRINFO_ERROR -109
"getaddrinfo" function error
Definition at line 294 of file flom_errors.h.
#define FLOM_RC_GETIFADDRS_ERROR -110
"getifaddrs" function error
Definition at line 298 of file flom_errors.h.
#define FLOM_RC_GETNAMEINFO_ERROR -111
"getnameinfo" function error
Definition at line 302 of file flom_errors.h.
#define FLOM_RC_GETSOCKNAME_ERROR -112
"getsockname" function error
Definition at line 306 of file flom_errors.h.
#define FLOM_RC_GETSOCKOPT_ERROR -113
"getsockopt" function error
Definition at line 310 of file flom_errors.h.
#define FLOM_RC_GETTIMEOFDAY_ERROR -114
"gettimeofday" function error
Definition at line 314 of file flom_errors.h.
#define FLOM_RC_INET_NTOP_ERROR -115
"inet_ntop" function error
Definition at line 318 of file flom_errors.h.
#define FLOM_RC_INTERNAL_ERROR -1
Internal error: unrecoverable status!
Definition at line 145 of file flom_errors.h.
#define FLOM_RC_INVALID_AI_FAMILY_ERROR -18
Address family is not a valid IP address family (AF_INET, AF_INET6)
Definition at line 214 of file flom_errors.h.
#define FLOM_RC_INVALID_IP_ADDRESS -19
The specified IP address is not valid for the current function
Definition at line 218 of file flom_errors.h.
#define FLOM_RC_INVALID_IPV6_NETWORK_INTERFACE -20
The specified network interface is not valid for IPv6 networking
Definition at line 222 of file flom_errors.h.
#define FLOM_RC_INVALID_MSG_LENGTH -10
The length of the message differs from prefix
Definition at line 182 of file flom_errors.h.
#define FLOM_RC_INVALID_OPTION -5
A specified option is not valid
Definition at line 162 of file flom_errors.h.
#define FLOM_RC_INVALID_PREFIX_SIZE -8
The number of chars of the prefix of the message
Definition at line 174 of file flom_errors.h.
#define FLOM_RC_INVALID_PROPERTY_VALUE -11
The XML message is malformed and can not be processed
Definition at line 186 of file flom_errors.h.
#define FLOM_RC_INVALID_RESOURCE_NAME -14
Specified resource name is not valid
Definition at line 198 of file flom_errors.h.
#define FLOM_RC_INVALID_TIMESTAMP_FORMAT -25
The format for a timestamp resource is not valid
Definition at line 243 of file flom_errors.h.
#define FLOM_RC_LISTEN_ERROR -116
"listen" function error
Definition at line 322 of file flom_errors.h.
#define FLOM_RC_LOCALTIME_R_ERROR -117
"localtime_r" function error
Definition at line 326 of file flom_errors.h.
#define FLOM_RC_LOCK_BUSY +4
The lock can not be obtained because the resource is already locked
Definition at line 116 of file flom_errors.h.
#define FLOM_RC_LOCK_CANT_LOCK +3
The lock can not be obtained, generic issue
Definition at line 120 of file flom_errors.h.
#define FLOM_RC_LOCK_CANT_WAIT +5
The lock can not be obtained because the requester can not wait resource availability
Definition at line 112 of file flom_errors.h.
#define FLOM_RC_LOCK_ENQUEUED +1
The lock can not be obtained now, but the request was enqueued
Definition at line 129 of file flom_errors.h.
#define FLOM_RC_LOCK_IMPOSSIBLE +6
The lock can not be obtained because the resource can not host the request (example: asking 12 numeric unities for a resource defined with a total quantity of 9)
Definition at line 107 of file flom_errors.h.
#define FLOM_RC_LOCK_WAIT_RESOURCE +2
The resource does not exist and the request must ask for resource creation
Definition at line 125 of file flom_errors.h.
#define FLOM_RC_MALLOC_ERROR -118
"malloc"/"g_malloc" function error
Definition at line 330 of file flom_errors.h.
#define FLOM_RC_MSG_DESERIALIZE_ERROR -16
Error occurred while deserializing XML message
Definition at line 206 of file flom_errors.h.
#define FLOM_RC_NETWORK_EVENT_ERROR -3
Unespected network event
Definition at line 153 of file flom_errors.h.
#define FLOM_RC_NETWORK_TIMEOUT +9
A network operation timed out
Definition at line 93 of file flom_errors.h.
#define FLOM_RC_NEW_DIRECT_BYTE_BUFFER_ERROR -302
JNI "NewDirectByteBuffer" function error
Definition at line 488 of file flom_errors.h.
#define FLOM_RC_NEW_OBJ -21
Error while creating a new object in the heap
Definition at line 226 of file flom_errors.h.
#define FLOM_RC_NO_CERTIFICATE -22
The peer did not supply a valid certificate for a TLS/SSL connection
Definition at line 230 of file flom_errors.h.
#define FLOM_RC_NO_TLS_CONNECTION -24
The connection is not a TLS connection, but a TLS operation was requested
Definition at line 239 of file flom_errors.h.
#define FLOM_RC_NULL_OBJECT -4
A passed object/option/arg is NULL and it can NOT be inferred from a default value
Definition at line 158 of file flom_errors.h.
#define FLOM_RC_OBJ_CORRUPTED -6
A corrupted object has been discovered
Definition at line 166 of file flom_errors.h.
#define FLOM_RC_OK 0
Successfully completion
Definition at line 137 of file flom_errors.h.
Referenced by flom::FlomHandle::FlomHandle(), and flom::FlomHandle::~FlomHandle().
#define FLOM_RC_OPEN_ERROR -119
"open" function error
Definition at line 334 of file flom_errors.h.
#define FLOM_RC_OUT_OF_RANGE -7
A parameter passed to a function is OUT OF RANGE
Definition at line 170 of file flom_errors.h.
#define FLOM_RC_PIPE_ERROR -120
"pipe" function error
Definition at line 338 of file flom_errors.h.
#define FLOM_RC_POLL_ERROR -121
"poll" function error
Definition at line 342 of file flom_errors.h.
#define FLOM_RC_PROTOCOL_ERROR -13
A routine has been invoked in an improper context
Definition at line 194 of file flom_errors.h.
#define FLOM_RC_PROTOCOL_LEVEL_MISMATCH -15
Client and server are not using the same communication protocol
Definition at line 202 of file flom_errors.h.
#define FLOM_RC_READ_ERROR -122
"read" function error
Definition at line 346 of file flom_errors.h.
#define FLOM_RC_REALPATH_ERROR -123
"realpath" function error
Definition at line 350 of file flom_errors.h.
#define FLOM_RC_RECV_ERROR -124
"recv" function error
Definition at line 354 of file flom_errors.h.
#define FLOM_RC_RECVFROM_ERROR -125
"recvfrom" function error
Definition at line 358 of file flom_errors.h.
#define FLOM_RC_REGCOMP_ERROR -126
"regcomp" function error
Definition at line 362 of file flom_errors.h.
#define FLOM_RC_REGEXEC_ERROR -127
"regexec" function error
Definition at line 366 of file flom_errors.h.
#define FLOM_RC_RESOURCE_INIT_ERROR -26
The resource can't be initialized
Definition at line 247 of file flom_errors.h.
#define FLOM_RC_RESOURCE_IS_NOT_TRANSACTIONAL +12
A transactional operation has been requested for non transactional resource. See also flom_handle_unlock_rollback method
Definition at line 79 of file flom_errors.h.
#define FLOM_RC_SEND_ERROR -128
"send" function error
Definition at line 370 of file flom_errors.h.
#define FLOM_RC_SENDTO_ERROR -129
"sendto" function error
Definition at line 374 of file flom_errors.h.
#define FLOM_RC_SETSID_ERROR -130
"setsid" function error
Definition at line 378 of file flom_errors.h.
#define FLOM_RC_SETSOCKOPT_ERROR -131
"setsockopt" function error
Definition at line 382 of file flom_errors.h.
#define FLOM_RC_SIGACTION_ERROR -132
"sigaction" function error
Definition at line 386 of file flom_errors.h.
#define FLOM_RC_SIGNAL_ERROR -133
"signal" function error
Definition at line 390 of file flom_errors.h.
#define FLOM_RC_SNPRINTF_ERROR -135
"snprintf" function error (truncation)
Definition at line 398 of file flom_errors.h.
#define FLOM_RC_SOCKET_ERROR -134
"socket" function error
Definition at line 394 of file flom_errors.h.
#define FLOM_RC_SSL_ACCEPT_ERROR -405
OpenSSL "SSL_acceept" function error
Definition at line 515 of file flom_errors.h.
#define FLOM_RC_SSL_CONNECT_ERROR -406
OpenSSL "SSL_connect" function error
Definition at line 519 of file flom_errors.h.
#define FLOM_RC_SSL_CTX_CHECK_PRIVATE_KEY_ERROR -400
OpenSSL "SSL_CTX_check_private_key" function error
Definition at line 495 of file flom_errors.h.
#define FLOM_RC_SSL_CTX_LOAD_VERIFY_LOCATIONS_ERROR -401
OpenSSL "SSL_CTX_load_verify_locations" function error
Definition at line 499 of file flom_errors.h.
#define FLOM_RC_SSL_CTX_NEW_ERROR -402
OpenSSL "SSL_CTX_new" function error
Definition at line 503 of file flom_errors.h.
#define FLOM_RC_SSL_CTX_USE_CERTIFICATE_FILE_ERROR -403
OpenSSL "SSL_CTX_use_certificate_file" function error
Definition at line 507 of file flom_errors.h.
#define FLOM_RC_SSL_CTX_USE_PRIVATEKEY_FILE_ERROR -404
OpenSSL "SSL_CTX_use_PrivateKey_file" function error
Definition at line 511 of file flom_errors.h.
#define FLOM_RC_SSL_GET_VERIFY_RESULT_ERROR -407
OpenSSL "SSL_get_verify_result" function error
Definition at line 523 of file flom_errors.h.
#define FLOM_RC_SSL_NEW_ERROR -408
OpenSSL "SSL_new" function error
Definition at line 527 of file flom_errors.h.
#define FLOM_RC_SSL_READ_ERROR -409
OpenSSL "SSL_read" function error
Definition at line 531 of file flom_errors.h.
#define FLOM_RC_SSL_SET_EX_DATA_ERROR -410
OpenSSL "SSL_set_ex_data" function error
Definition at line 535 of file flom_errors.h.
#define FLOM_RC_SSL_SET_FD_ERROR -411
OpenSSL "SSL_set_fd" function error
Definition at line 539 of file flom_errors.h.
#define FLOM_RC_SSL_WRITE_ERROR -412
OpenSSL "SSL_write" function error
Definition at line 543 of file flom_errors.h.
#define FLOM_RC_TLS_NO_VALID_METHOD -413
No valid TLS/SSL method was found
Definition at line 547 of file flom_errors.h.
#define FLOM_RC_UNIQUE_ID_DOES_NOT_MATCH -23
The unique ID sent by the peer does not match the CN field inside the X509 provided certificate
Definition at line 235 of file flom_errors.h.
#define FLOM_RC_UNLINK_ERROR -136
"unlink" function error
Definition at line 402 of file flom_errors.h.
#define FLOM_RC_WAIT_ERROR -137
"wait" function error
Definition at line 406 of file flom_errors.h.
#define FLOM_RC_WRITE_ERROR -138
"write" function error
Definition at line 410 of file flom_errors.h.
Function Documentation
const char* flom_strerror (int ret_cod)
PUBLIC METHOD
Retrieve the description associated to a return/reason code
Parameters
ret_cod IN return/reason code of the desired description
Returns
a const string containing a description of reason code
Referenced by flom::FlomHandle::FlomHandle(), flom::FlomException::getReturnCodeText(), and flom::FlomHandle::~FlomHandle().
Copyright © 2013-2020, Christian Ferrari tiian@users.sourceforge.net