libflom: FLoM (Free Lock Manager) client library
flom::FlomHandle Class Reference
#include <FlomHandle.hh>
Public Member Functions
FlomHandle ()
int getDiscoveryAttempts ()
int getDiscoveryTimeout ()
int getDiscoveryTtl ()
string getLockedElement ()
const char * getLockedElementAsCStr ()
flom_lock_mode_t getLockMode ()
string getMulticastAddress ()
const char * getMulticastAddressAsCStr ()
int getMulticastPort ()
int getResourceCreate ()
int getResourceIdleLifespan ()
string getResourceName ()
const char * getResourceNameAsCStr ()
int getResourceQuantity ()
int getResourceTimeout ()
string getSocketName ()
const char * getSocketNameAsCStr ()
string getTraceFilename ()
const char * getTraceFilenameAsCStr ()
string getUnicastAddress ()
const char * getUnicastAddressAsCStr ()
int getUnicastPort ()
int lock ()
int setDiscoveryAttempts (int value)
int setDiscoveryTimeout (int value)
int setDiscoveryTtl (int value)
int setLockMode (flom_lock_mode_t value)
void setMulticastAddress (const string &value)
int setMulticastAddress (const char *value)
int setMulticastPort (int value)
int setResourceCreate (int value)
int setResourceIdleLifespan (int value)
int setResourceName (const string &value)
int setResourceName (const char *value)
int setResourceQuantity (int value)
int setResourceTimeout (int value)
int setSocketName (const string &value)
int setSocketName (const char *value)
int setTraceFilename (const string &value)
int setTraceFilename (const char *value)
void setUnicastAddress (const string &value)
int setUnicastAddress (const char *value)
int setUnicastPort (int value)
int unlock ()
~FlomHandle ()
Detailed Description
This class provides C++ abstraction to C flom_handle_t type
Definition at line 85 of file FlomHandle.hh.
Constructor & Destructor Documentation
flom::FlomHandle::FlomHandle () [inline]
Definition at line 93 of file FlomHandle.hh.
References flom_handle_init(), FLOM_RC_OK, and flom_strerror().
flom::FlomHandle::~FlomHandle () [inline]
Definition at line 102 of file FlomHandle.hh.
References flom_handle_clean(), FLOM_RC_OK, and flom_strerror().
Member Function Documentation
int flom::FlomHandle::getDiscoveryAttempts () [inline]
Gets the maximum number of attempts that will be tryed during auto-discovery phase using UDP/IP multicast (see getMulticastAddress, getMulticastPort). The current value can be altered using method setDiscoveryAttempts
Returns:
the current value
Definition at line 166 of file FlomHandle.hh.
References flom_handle_get_discovery_attempts().
int flom::FlomHandle::getDiscoveryTimeout () [inline]
Gets the number of milliseconds between two consecutive attempts that will be tryed during auto-discovery phase using UDP/IP multicast (see getMulticastAddress, getMulticastPort). The current value can be altered using method setDiscoveryTimeout
Returns:
the current value
Definition at line 190 of file FlomHandle.hh.
References flom_handle_get_discovery_timeout().
int flom::FlomHandle::getDiscoveryTtl () [inline]
Gets the UDP/IP multicast TTL parameter used during auto-discovery phase; for a definition of the parameter, see http://www.tldp.org/HOWTO/Multicast-HOWTO-2.html . The current value can be altered using method setDiscoveryTtl
Returns:
the current value
Definition at line 213 of file FlomHandle.hh.
References flom_handle_get_discovery_ttl().
string flom::FlomHandle::getLockedElement () [inline]
Gets the name of the locked element if the resource is of type set.
Note 1: this method can be used only after lock and before unlock
Note 2: this method can be used only when locking a resource of type "resource set"
Note 3: the return string must copied as soon as possible to a different place because it's a dynamic string removed by unlock
Returns:
the name of the locked element
Definition at line 154 of file FlomHandle.hh.
References flom_handle_get_locked_element().
const char* flom::FlomHandle::getLockedElementAsCStr () [inline]
Gets the name of the locked element if the resource is of type set.
Note 1: this method can be used only after lock and before unlock
Note 2: this method can be used only when locking a resource of type "resource set"
Note 3: the return string must copied as soon as possible to a different place because it's a dynamic string removed by unlock
Returns:
the name of the locked element
Definition at line 139 of file FlomHandle.hh.
References flom_handle_get_locked_element().
flom_lock_mode_t flom::FlomHandle::getLockMode () [inline]
Gets lock mode property: how a simple or hierarchical resource will be locked when method lock is called; FLoM supports the same lock mode semantic proposed by DLM, see http://en.wikipedia.org/wiki/Distributed_lock_manager#Lock_modes for a detailed explanation . The current value can be altered using method setLockMode
Returns:
the current value
Definition at line 237 of file FlomHandle.hh.
References flom_handle_get_lock_mode().
string flom::FlomHandle::getMulticastAddress () [inline]
Gets the multicast address: the IP address (or a network name that the system can resolve) of the IP multicast group that must be contacted to reach FLoM daemon (server) using UDP/IP; see also getMulticastPort. The current value can be altered using method setMulticastAddress.
Returns:
the current value as a standard C++ string
Definition at line 273 of file FlomHandle.hh.
References flom_handle_get_multicast_address().
const char* flom::FlomHandle::getMulticastAddressAsCStr () [inline]
Gets the multicast address: the IP address (or a network name that the system can resolve) of the IP multicast group that must be contacted to reach FLoM daemon (server) using UDP/IP; see also getMulticastPort. The current value can be altered using method setMulticastAddress.
Returns:
the current value as a null terminated C string
Definition at line 262 of file FlomHandle.hh.
References flom_handle_get_multicast_address().
int flom::FlomHandle::getMulticastPort () [inline]
Gets the UDP/IP multicast port that must be used to contact the FLoM daemon (server) using UDP/IP; see also getMulticastAddress. The current value can be altered using method setMulticastPort.
Returns:
the current value
Definition at line 307 of file FlomHandle.hh.
References flom_handle_get_multicast_port().
int flom::FlomHandle::getResourceCreate () [inline]
Gets "resource create" boolean property: it specifies if method lock can create a new resource when the specified one is not defined; the default value is TRUE. The current value can be altered using method setResourceCreate.
Returns:
the current value
Definition at line 329 of file FlomHandle.hh.
References flom_handle_get_resource_create().
int flom::FlomHandle::getResourceIdleLifespan () [inline]
Gets "resource idle lifespan" property: it specifies how many milliseconds a resource will be kept after the last locker released it; the expiration is necessary to avoid useless resource allocation. The current value can be altered using method setResourceIdleLifespan.
Returns:
the current value
Definition at line 353 of file FlomHandle.hh.
References flom_handle_get_resource_idle_lifespan().
string flom::FlomHandle::getResourceName () [inline]
Gets the resource name: the name of the resource that can be locked and unlocked using lock and unlock methods. The current value can be altered using method setResourceName.
Returns:
the current value as a C++ standard string
Definition at line 383 of file FlomHandle.hh.
References flom_handle_get_resource_name().
const char* flom::FlomHandle::getResourceNameAsCStr () [inline]
Gets the resource name: the name of the resource that can be locked and unlocked using lock and unlock methods. The current value can be altered using method setResourceName.
Returns:
the current value as a null terminated C string
Definition at line 375 of file FlomHandle.hh.
References flom_handle_get_resource_name().
int flom::FlomHandle::getResourceQuantity () [inline]
Gets "resource quantity" property: the number of units that will be locked and unlocked using lock and unlock methods. The current value can be altered using method setResourceQuantity. NOTE: this property applies to "numeric resources" only.
Returns:
the current value
Definition at line 423 of file FlomHandle.hh.
References flom_handle_get_resource_quantity().
int flom::FlomHandle::getResourceTimeout () [inline]
Gets "resource timeout" property: how long a lock operation (see lock) will wait if the resource is locked by another requester. The current value can be altered using method setResourceTimeout.
Returns:
the current value:
0: no wait
>0: maximum number of milliseconds to wait
<0: unlimited wait
Definition at line 449 of file FlomHandle.hh.
References flom_handle_get_resource_timeout().
string flom::FlomHandle::getSocketName () [inline]
Gets the socket name: the AF_LOCAL/AF_UNIX socket name that must be used to contact a local FLoM daemon (server). The current value can be altered using method setSocketName.
Returns:
the current value as a C++ standard string
Definition at line 481 of file FlomHandle.hh.
References flom_handle_get_socket_name().
const char* flom::FlomHandle::getSocketNameAsCStr () [inline]
Gets the socket name: the AF_LOCAL/AF_UNIX socket name that must be used to contact a local FLoM daemon (server). The current value can be altered using method setSocketName.
Returns:
the current value as a C null terminated string
Definition at line 473 of file FlomHandle.hh.
References flom_handle_get_socket_name().
string flom::FlomHandle::getTraceFilename () [inline]
Gets the trace filename: the name (absolute or relative path) used by libflom (FLoM client library) to record trace messages. The current value can be altered using method setTraceFilename.
Returns:
the current value as a C++ standard string
Definition at line 518 of file FlomHandle.hh.
References flom_handle_get_trace_filename().
const char* flom::FlomHandle::getTraceFilenameAsCStr () [inline]
Gets the trace filename: the name (absolute or relative path) used by libflom (FLoM client library) to record trace messages. The current value can be altered using method setTraceFilename.
Returns:
the current value as a C null terminated string
Definition at line 510 of file FlomHandle.hh.
References flom_handle_get_trace_filename().
string flom::FlomHandle::getUnicastAddress () [inline]
Gets the unicast address: the IP address (or a network name that the system can resolve) of the host that must be contacted to reach FLoM daemon (server) using TCP/IP; see also getUnicastPort. The current value can be altered using method setUnicastAddress.
Returns:
the current value as a C++ standard string
Definition at line 563 of file FlomHandle.hh.
References flom_handle_get_unicast_address().
const char* flom::FlomHandle::getUnicastAddressAsCStr () [inline]
Gets the unicast address: the IP address (or a network name that the system can resolve) of the host that must be contacted to reach FLoM daemon (server) using TCP/IP; see also getUnicastPort. The current value can be altered using method setUnicastAddress.
Returns:
the current value as a C null terminated string
Definition at line 552 of file FlomHandle.hh.
References flom_handle_get_unicast_address().
int flom::FlomHandle::getUnicastPort () [inline]
Gets the TCP/IP unicast port that must be used to contact the FLoM daemon (server) using TCP/IP; see also getUnicastAddress. The current value can be altered using method setUnicastPort.
Returns:
the current value
Definition at line 597 of file FlomHandle.hh.
References flom_handle_get_unicast_port().
int flom::FlomHandle::lock () [inline]
Locks the (logical) resource linked to this handle; the resource MUST be unlocked using method unlock when the lock condition is no more necessary.
Returns:
a reason code (see file flom_errors.h)
Definition at line 118 of file FlomHandle.hh.
References flom_handle_lock().
int flom::FlomHandle::setDiscoveryAttempts (int value) [inline]
Sets the maximum number of attempts that will be tryed during auto-discovery phase using UDP/IP multicast (see setMulticastAddress, setMulticastPort). The current value can be inspected using method getDiscoveryAttempts
Parameters:
value (Input): the new value
Returns:
FLOM_RC_OK or FLOM_RC_API_IMMUTABLE_HANDLE
Definition at line 178 of file FlomHandle.hh.
References flom_handle_set_discovery_attempts().
int flom::FlomHandle::setDiscoveryTimeout (int value) [inline]
Sets the number of milliseconds between two consecutive attempts that will be tryed during auto-discovery phase using UDP/IP multicast (see setMulticastAddress, setMulticastPort). The current value can be inspected using method getDiscoveryTimeout.
Parameters:
value (Input): the new value
Returns:
FLOM_RC_OK or FLOM_RC_API_IMMUTABLE_HANDLE
Definition at line 203 of file FlomHandle.hh.
References flom_handle_set_discovery_timeout().
int flom::FlomHandle::setDiscoveryTtl (int value) [inline]
Sets the UDP/IP multicast TTL parameter used during auto-discovery phase; for a definition of the parameter, see http://www.tldp.org/HOWTO/Multicast-HOWTO-2.html . The current value can be inspected using method getDiscoveryTtl.
Parameters:
value (Input): the new value
Returns:
FLOM_RC_OK or FLOM_RC_API_IMMUTABLE_HANDLE
Definition at line 225 of file FlomHandle.hh.
References flom_handle_set_discovery_ttl().
int flom::FlomHandle::setLockMode (flom_lock_mode_t value) [inline]
Sets lock mode property: how a simple or hierarchical resource will be locked when method lock is called; FLoM supports the same lock mode semantic proposed by DLM, see http://en.wikipedia.org/wiki/Distributed_lock_manager#Lock_modes for a detailed explanation . The current value can be inspected using method getLockMode
Parameters:
value (Input): the new value
Returns:
FLOM_RC_OK or FLOM_RC_API_IMMUTABLE_HANDLE
Definition at line 250 of file FlomHandle.hh.
References flom_handle_set_lock_mode().
void flom::FlomHandle::setMulticastAddress (const string & value) [inline]
Sets the multicast address: the IP address (or a network name that the system can resolve) of the IP multicast group that must be contacted to reach FLoM daemon (server) using UDP/IP; see also setMulticastPort. The current value can be inspected using method getMulticastAddress.
Parameters:
value (Input): the new value (C++ standard string)
Definition at line 298 of file FlomHandle.hh.
References flom_handle_set_multicast_address().
int flom::FlomHandle::setMulticastAddress (const char * value) [inline]
Sets the multicast address: the IP address (or a network name that the system can resolve) of the IP multicast group that must be contacted to reach FLoM daemon (server) using UDP/IP; see also setMulticastPort. The current value can be inspected using method getMulticastAddress.
Parameters:
value (Input): the new value (C null terminated string)
Returns:
FLOM_RC_OK or FLOM_RC_API_IMMUTABLE_HANDLE
Definition at line 287 of file FlomHandle.hh.
References flom_handle_set_multicast_address().
int flom::FlomHandle::setMulticastPort (int value) [inline]
Sets the UDP/IP multicast port that must be used to contact the FLoM daemon (server) using UDP/IP; see also setMulticastAddress. The current value can be inspected using method getMulticastPort.
Parameters:
value (Input): the new value
Returns:
FLOM_RC_OK or FLOM_RC_API_IMMUTABLE_HANDLE
Definition at line 318 of file FlomHandle.hh.
References flom_handle_set_multicast_port().
int flom::FlomHandle::setResourceCreate (int value) [inline]
Sets "resource create" boolean property: it specifies if method lock can create a new resource when the specified one is not defined. The current value can be inspected using method getResourceCreate.
Parameters:
value (Input): the new value
Returns:
FLOM_RC_OK or FLOM_RC_API_IMMUTABLE_HANDLE
Definition at line 341 of file FlomHandle.hh.
References flom_handle_set_resource_create().
int flom::FlomHandle::setResourceIdleLifespan (int value) [inline]
Sets "resource idle lifespan" property: it specifies how many milliseconds a resource will be kept after the last locker released it; the expiration is necessary to avoid useless resource allocation. The current value can be inspected using method getResourceIdleLifespan.
Parameters:
value (Input): the new value
Returns:
FLOM_RC_OK or FLOM_RC_API_IMMUTABLE_HANDLE
Definition at line 366 of file FlomHandle.hh.
References flom_handle_set_resource_idle_lifespan().
int flom::FlomHandle::setResourceName (const string & value) [inline]
Sets the resource name: the name of the resource that can be locked and unlocked using lock and unlock methods. The current value can be inspected using method getResourceName. NOTE: the resource type is determined by its name; take a look to flom command man page (-r, --resource-name option) for an explanation of the resource name grammar.
Parameters:
value (Input): the new value (C++ standard string)
Returns:
a reason code (see file flom_errors.h)
FLOM_RC_OK or FLOM_RC_API_IMMUTABLE_HANDLE
Definition at line 412 of file FlomHandle.hh.
References flom_handle_set_resource_name().
int flom::FlomHandle::setResourceName (const char * value) [inline]
Sets the resource name: the name of the resource that can be locked and unlocked using lock and unlock methods. The current value can be inspected using method getResourceName. NOTE: the resource type is determined by its name; take a look to flom command man page (-r, --resource-name option) for an explanation of the resource name grammar.
Parameters:
value (Input): the new value (C null terminated string)
Returns:
FLOM_RC_OK or FLOM_RC_API_IMMUTABLE_HANDLE
Definition at line 398 of file FlomHandle.hh.
References flom_handle_set_resource_name().
int flom::FlomHandle::setResourceQuantity (int value) [inline]
Sets "resource quantity" property: the number of units that will be locked and unlocked using lock and unlock methods. The current value can be inspected using method getResourceQuantity. NOTE: this property applies to "numeric resources" only.
Parameters:
value (Input): the new value
Returns:
FLOM_RC_OK or FLOM_RC_API_IMMUTABLE_HANDLE
Definition at line 435 of file FlomHandle.hh.
References flom_handle_set_resource_quantity().
int flom::FlomHandle::setResourceTimeout (int value) [inline]
Sets "resource timeout" property: how long a lock operation (see lock) will wait if the resource is locked by another requester. The current value can be inspected using method getResourceTimeout.
Parameters:
value (Input): the new value:
0: no wait
>0: maximum number of milliseconds to wait
<0: unlimited wait
Returns:
FLOM_RC_OK or FLOM_RC_API_IMMUTABLE_HANDLE
Definition at line 464 of file FlomHandle.hh.
References flom_handle_set_resource_timeout().
int flom::FlomHandle::setSocketName (const string & value) [inline]
Sets the socket name: the AF_LOCAL/AF_UNIX socket name that must be used to contact a local FLoM daemon (server). The current value can be inspected using method getSocketName.
Parameters:
value (Input): the new value (C++ standard string)
Returns:
a reason code (see file flom_errors.h)
Definition at line 501 of file FlomHandle.hh.
References flom_handle_set_socket_name().
int flom::FlomHandle::setSocketName (const char * value) [inline]
Sets the socket name: the AF_LOCAL/AF_UNIX socket name that must be used to contact a local FLoM daemon (server). The current value can be inspected using method getSocketName.
Parameters:
value (Input): the new value (C null terminated string)
Returns:
a reason code (see file flom_errors.h)
Definition at line 492 of file FlomHandle.hh.
References flom_handle_set_socket_name().
int flom::FlomHandle::setTraceFilename (const string & value) [inline]
Sets the trace filename: the name (absolute or relative path) used by libflom (FLoM client library) to record trace messages. The current value can be inspected using method getTraceFilename.
Parameters:
value (Input): the new value (C++ standard string)
Returns:
FLOM_RC_OK
Definition at line 540 of file FlomHandle.hh.
References flom_handle_set_trace_filename().
int flom::FlomHandle::setTraceFilename (const char * value) [inline]
Sets the trace filename: the name (absolute or relative path) used by libflom (FLoM client library) to record trace messages. The current value can be inspected using method getTraceFilename.
Parameters:
value (Input): the new value (C null terminated string)
Returns:
FLOM_RC_OK
Definition at line 530 of file FlomHandle.hh.
References flom_handle_set_trace_filename().
void flom::FlomHandle::setUnicastAddress (const string & value) [inline]
Sets the unicast address: the IP address (or a network name that the system can resolve) of the host that must be contacted to reach FLoM daemon (server) using TCP/IP; see also setUnicastPort. The current value can be inspected using method getUnicastAddress.
Parameters:
value (Input): the new value (C++ standard string)
Definition at line 588 of file FlomHandle.hh.
References flom_handle_set_unicast_address().
int flom::FlomHandle::setUnicastAddress (const char * value) [inline]
Sets the unicast address: the IP address (or a network name that the system can resolve) of the host that must be contacted to reach FLoM daemon (server) using TCP/IP; see also setUnicastPort. The current value can be inspected using method getUnicastAddress.
Parameters:
value (Input): the new value (C null terminted string)
Returns:
FLOM_RC_OK or FLOM_RC_API_IMMUTABLE_HANDLE
Definition at line 577 of file FlomHandle.hh.
References flom_handle_set_unicast_address().
int flom::FlomHandle::setUnicastPort (int value) [inline]
Sets the TCP/IP unicast port that must be used to contact the FLoM daemon (server) using TCP/IP; see also setUnicastAddress. The current value can be inspected using method getUnicastPort.
Parameters:
value (Input): the new value
Returns:
FLOM_RC_OK or FLOM_RC_API_IMMUTABLE_HANDLE
Definition at line 607 of file FlomHandle.hh.
References flom_handle_set_unicast_port().
int flom::FlomHandle::unlock () [inline]
Unlocks the (logical) resource linked to this handle; the resource MUST be previously locked using method lock
Returns:
a reason code (see file flom_errors.h)
Definition at line 125 of file FlomHandle.hh.
References flom_handle_unlock().
The documentation for this class was generated from the following file:
FlomHandle.hh
Copyright © 2013-2015, Christian Ferrari tiian@users.sourceforge.net